// WF 2023051604037
// generated by AI, used in BrightBoard
// 控制当前窗口的亮度
package com.example;

import android.app.Activity;
import android.view.Window;
import android.view.WindowManager;

public class MyBrightnessHelper {
    public static void setWindowBrightness(Activity activity, float brightness) {
        Window window = activity.getWindow();
        WindowManager.LayoutParams layoutParams = window.getAttributes();
        layoutParams.screenBrightness = brightness; // 0.0f ~ 1.0f
        window.setAttributes(layoutParams);
    }
}
